swagger: '2.0'
info: 
  title: 'Animal Crossing: New Horizons API'
  version: '0.1'
  description: 'Animal Crossing: New Horizons API for fish, bugs, and fossils (at the moment)'
produces: 
  - application/json
paths:
  /fossils:
    get:
      tags: [Fossil]
      operationId: endpoints.get_fossils
      summary: Get all fossils
      responses:
        200:
          description: Return all fossils
          schema:
            type: object
            properties:
              fossils:
                type: array
                items:
                  $ref: '#/definitions/Fossil'
  /fossils/{fossil_id}:
    get:
      tags: [Fossil]
      operationId: endpoints.get_fossil
      summary: Get a single fossil
      parameters:
      - in: path
        name: fossil_id
        type: integer
        required: true
        description: ID of the fossil
      responses:
        200:
          description: Get a single fossil
          schema:
            $ref: '#/definitions/Fossil'
        404:
          description: Fish does not exist
  /fish:
    get:
      tags: [Fish]
      operationId: endpoints.get_fishes
      summary: Get all fish
      responses:
        200:
          description: Return a number of fish
          schema:
            type: object
            properties: 
              fish:
                type: array
                items:
                  $ref: '#/definitions/Fish'
  /fish/{fish_id}:
    get:
      tags: [Fish]
      operationId: endpoints.get_fish
      summary: Get the details of a single fish
      parameters:
      - in: path
        name: fish_id
        type: integer
        required: true
        description: Numeric ID of the fish
      responses:
        200:
          description: Return a fish
          schema:
            $ref: '#/definitions/Fish'
        404:
          description: Fish does not exist
  /bugs:
    get:
      tags: [Bug]
      operationId: endpoints.get_bugs
      summary: Get all bugs
      responses:
        200:
          description: Return a list of bugs
          schema:
            type: object
            properties:
              bugs:
                type: array
                items:
                  $ref: '#/definitions/Bug'
  /bugs/{bug_id}:
    get:
      tags: [Bug]
      operationId: endpoints.get_bug
      summary: Get the details of a bug
      parameters:
      - in: path
        name: bug_id
        type: integer
        required: true
        description: Numeric ID of the fish
      responses:
        200:
          description: Return the details of a bug
          schema:
            $ref: '#/definitions/Bug'
        404:
          description: Bug does not exist

definitions:
  Fossil:
    type: object
    properties:
      id:
        type: integer
        description: unique id
        readOnly: true
      name:
        type: string
        description: Name of the fossil
        minLength: 1
      imageUrl:
        type: string
        description: URL to the image of the fossil (if exists)
      price: 
        type: integer
      fossil_type:
        type: string
      group:
        type: string
      
  Fish:
    type: object
    properties:
      id: 
        type: integer
        description: unique id
        readOnly: true
      name: 
        type: string
        description: Name of the fish
        minLength: 1
        maxLength: 30
      imageUrl: 
        type: string
        description: URL to the image of the fish
      price:
        type: integer
      location:
        type: string
      shadowSize: 
        type: integer
      time:
        type: string
      month:
        type: string
      critter_type:
        type: string

  Bug:
    type: object
    properties:
      id:
        type: integer
        description: unique id
        readOnly: true
      name: 
        type: string
        description: Name of the bug
        minLength: 1
        maxLength: 30
      imageUrl: 
        type: string
        description: URL to the image of the bug
      price:
        type: integer
      location:
        type: string
      time:
        type: string
      month:
        type: string
      critter_type:
        type: string        